root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/app/main.go"
bin = "./tmp/main"
exclude_dir = ["assets", "build", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]
# This log file places in your tmpdir.
log = "air_errors.log"
# It's not necessary to notify (log) after each file watch.
delay = 1000 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete binary after air ends.
clean = true